### ISSUE TITLE
Splunk Platform Upgrade Readiness App warning on splunklib Py files

### ISSUE THREAD

**Issue by guilhemmarchand** [splunk/splunk-sdk-python#321]
Hi,

Currently reviewing Python3 compatibility with the Splunk Platform Upgrade Readiness App, there are several warnings if you include the Python SDK splunklib in a Splunk app:

![image](https://user-images.githubusercontent.com/7503059/80872542-74323d80-8caa-11ea-8ddd-8452a82a2257.png)

Example:

![image](https://user-images.githubusercontent.com/7503059/80872549-844a1d00-8caa-11ea-8252-4261b68de265.png)

While these warnings do not necessary really mean an impact on Python3 compatibility, many customers are going to the steps of validating the Splunk apps compatibility and might contact apps developers for these questions.

Should this be reviewed and fixed ?

**Comment by fantavlik** [comment]
Thanks all, we'll be working with the Splunk Platform Upgrade Readiness App team to remove these warnings. Please disregard them at this time.

**Comment by tkoeberl** [comment]
Seems still the case. Does that mean I can ignore all warnings?

**Comment by ncanumalla-splunk** [comment]
@tkoeberl Please continue to ignore the warnings. The Splunk Platform Upgrade Readiness App team is working on this. We will post an update here once the fix is released.

**Comment by adilovesgh** [comment]
Hello, has there been a fix implemented yet for the these readiness warnings? Or should we still continue to ignore them?

**Comment by ncanumalla-splunk** [comment]
@adilovesgh @tkoeberl The Splunk Platform Upgrade Readiness App is no longer taking new updates and is replaced by the [Upgrade Readiness App](https://splunkbase.splunk.com/app/5483/). The scan of the splunklib is ignored and these warnings should no longer appear in the latest version 3.0.2. Please update to using the latest [Upgrade Readiness App](https://splunkbase.splunk.com/app/5483/).  Closing for now and can be reopened if there are further issues.
